version: "3.8"

services:
  hrsystemfrontend:
    image: ${DOCKERHUB_USERNAME}/hrsystemfrontend:${IMAGE_TAG}
    container_name: hrsystemfrontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - hrfrontend

networks:
  hrfrontend:
    driver: bridge