version: "3.8"
 
services:
  hrsystemfrontend:
    image: ${DOCKERHUB_USERNAME}/hrsystembackend:${IMAGE_TAG}
    container_name: hrsystemfrontend
    ports:
      - "3000:80"
    networks:
      - hrfrontend
    environment:
      NODE_ENV: UAT
    restart: unless-stopped
 
networks:
  hrfrontend:
    driver: bridge