name: UAT CI/CD Deployment to VPS
on:
  push:
    branches:
      - uat

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg BACKEND_API_URL=http://131.153.49.2:5093 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/hrsystemfrontend:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hrsystemfrontend:${{ github.sha }}

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy via SSH
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no \
          ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} \
          -p ${{ secrets.VPS_PORT }} << EOF

          cd /home/cldhrsys/ai-hr-sys/AI_HR_System_FE
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    
          export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          export IMAGE_TAG=${{ github.sha }}

          docker compose pull
          docker compose up -d

          EOF